name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y setools lzip wine patchelf e2fsprogs python3-pip aria2 p7zip-full attr xz-utils unzip cabextract
          sudo wget -P /usr/local/bin/ https://raw.githubusercontent.com/GroundFishles/winetricks/master/src/winetricks
          sudo chmod +x /usr/local/bin/winetricks
          pip list --disable-pip-version-check | grep -E "^requests " >/dev/null 2>&1 || python3 -m pip install requests
          winetricks list-installed | grep -E "^msxml6" >/dev/null 2>&1 || winetricks msxml6 || abort
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build WSA
        run: |
          cd ./MagiskOnWSALocal
          scripts/build.sh \
          --arch x64 \
          --release-type WIF \
          --magisk-ver stable \
          --gapps-brand MindTheGapps \
          --gapps-variant pico \
          --root-sol magisk
      - name: Archiving and compressing artifact
        run: |
          cd MagiskOnWSALocal/output
          7z a -tzip -mx=1 ../WSA.zip .
          cd ../..
      - name: Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: MagiskOnWSALocal/WSA.zip
          tag_name: WSA
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
