name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build Magusk On WSA
        run: |
          cd ./MagiskOnWSALocal
          chmod 777 ./build.sh
          ./build.sh --help
